import { z } from 'zod';
import { readCsv,demoCases } from './returns';
export const orderSchema=z.object({orderId:z.string().trim().min(1).max(80),product:z.string().trim().min(1).max(160),amountPaid:z.number().finite().min(0).max(1000000),amountRefunded:z.number().finite().min(0).max(1000000),expectedSerial:z.string().trim().max(100),trackingNumber:z.string().trim().max(120).default(''),source:z.string().trim().min(1).max(80).default('Order CSV'),demo:z.boolean().default(false)}).refine(c=>c.amountRefunded<=c.amountPaid,{message:'Refunded amount cannot exceed paid amount'});
export type OrderRecord=z.infer<typeof orderSchema>&{importedAt?:string};
export function orderKey(c:{orderId:string;product:string;demo?:boolean}){return JSON.stringify([c.demo===true,c.orderId.trim().toUpperCase(),c.product.trim().toLowerCase()]);}
export const orderHeaders=['order_id','product','paid_amount','refunded_amount','expected_serial','tracking_number','source'];
export const demoOrders=demoCases.map((c,i)=>({...orderSchema.parse({orderId:c.orderId,product:c.product,amountPaid:c.amount,amountRefunded:0,expectedSerial:`DEMO-${1042+i}`,trackingNumber:`SAMPLE-TRACK-${1042+i}`,source:'Fictional demo records',demo:true})}));
export function orderCsv(records:OrderRecord[]){return [orderHeaders,...records.map(c=>[c.orderId,c.product,c.amountPaid,c.amountRefunded,c.expectedSerial,c.trackingNumber,c.source])].map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');}
export function parseOrders(text:string){const rows=readCsv(text),head=rows.shift()!.map(x=>x.replace(/^\uFEFF/,'').trim());if(orderHeaders.slice(0,5).some(x=>!head.includes(x)))throw new Error('Use the order template: required columns are missing');if(rows.length>500)throw new Error('Import up to 500 order records');const keys=new Set<string>();return rows.map((r,i)=>{const o=Object.fromEntries(head.map((h,n)=>[h,(r[n]??'').trim()]));if(!o.paid_amount||!o.refunded_amount)throw new Error(`Row ${i+2}: paid_amount and refunded_amount are required`);const c=orderSchema.safeParse({orderId:o.order_id,product:o.product,amountPaid:Number(o.paid_amount),amountRefunded:Number(o.refunded_amount),expectedSerial:o.expected_serial,trackingNumber:o.tracking_number||'',source:o.source||'Order CSV',demo:false});if(!c.success)throw new Error(`Row ${i+2}: ${c.error.issues[0].message}`);const key=orderKey(c.data);if(keys.has(key))throw new Error(`Row ${i+2}: duplicate order and product. Consolidate the line before importing.`);keys.add(key);return c.data;});}
