'use client';
import { useEffect, useRef, useState } from 'react';
import { ShieldCheck, Upload, Download, PackageCheck, ScanLine, Files, Check, Search, ClipboardList, RefreshCw } from 'lucide-react';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Toaster,toast } from 'sonner';
import { ReturnCase,signals,priority,demoCases,csv,parseCsv } from '@/lib/returns';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const decisions=['Open','Ready for refund','Request evidence','Inspect item'];
async function api(method='GET',body?:unknown){const res=await fetch('/api/returns',{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
function download(name:string,content:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export default function Home(){
 const [cases,setCases]=useState<ReturnCase[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<ReturnCase|null>(null),[decision,setDecision]=useState('Open'),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[importOpen,setImportOpen]=useState(false),[parsed,setParsed]=useState<ReturnType<typeof parseCsv>>([]),[fileName,setFileName]=useState(''),[importError,setImportError]=useState(''),[busy,setBusy]=useState(false);
 const file=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setError('');try{const d=await api();setCases(d.cases);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 function open(c:ReturnCase){setSelected(c);setDecision(c.decision);setNote(c.note);}
 async function seed(){setBusy(true);try{const r=await api('POST',{demo:true});await load();toast.success(`${r.added} sample returns added${r.skipped?`; ${r.skipped} already loaded`:''}`);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!selected)return;setSaving(true);try{const r=await api('PATCH',{id:selected.id,revision:selected.revision,decision,note});setCases(old=>old.map(c=>c.id===r.case.id?r.case:c));setSelected(r.case);toast.success('Review saved');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function chooseFile(f?:File){setImportError('');setParsed([]);if(!f)return;setFileName(f.name);if(f.size>1000000){setImportError('Choose a CSV smaller than 1 MB');return;}try{setParsed(parseCsv(await f.text()));}catch(e){setImportError((e as Error).message);}}
 async function commitImport(){setBusy(true);try{const r=await api('POST',{cases:parsed});await load();setImportOpen(false);setParsed([]);toast.success(`${r.added} returns imported. ${r.skipped} existing IDs skipped.`);}catch(e){setImportError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'list_return_cases',description:'Read saved return cases and evidence flags in the current review workspace.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const d=await api();return {cases:d.cases.map((c:ReturnCase)=>({id:c.id,decision:c.decision,flags:signals(c)}))};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 const openCases=cases.filter(c=>c.decision==='Open'),flagged=openCases.filter(c=>signals(c).length),inspection=openCases.filter(c=>priority(c)==='Inspection');
 const visible=cases.filter(c=>(tab==='all'||tab==='open'&&c.decision==='Open'||tab==='reviewed'&&c.decision!=='Open')&&`${c.id} ${c.orderId} ${c.customer} ${c.product}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const rank=(c:ReturnCase)=>c.decision!=='Open'?3:priority(c)==='Inspection'?0:priority(c)==='Evidence needed'?1:2;return rank(a)-rank(b);});
 return <><Toaster richColors position="bottom-right"/><header className="topbar"><div className="brand"><span className="mark"><ShieldCheck size={22}/></span>ReturnCheck<span className="mvp">MVP</span></div><div className="topmeta">RETURN OPERATIONS<span className="avatar">TT</span></div></header>
 <main className="workspace"><div className="pagehead"><div><p className="eyebrow">WORKSPACE / RETURNS</p><h1>Review before you refund.</h1><p className="subtitle">A clear view of the evidence behind every return.</p></div><div className="actions"><button className="button secondary" onClick={seed} disabled={busy||loading}><Files size={16}/>Load sample returns</button><button className="button primary" onClick={()=>{setImportOpen(true);setImportError('');}}><Upload size={16}/>Import CSV</button></div></div>
 <section className="metrics" aria-label="Return summary"><div><span>Open returns</span><strong>{openCases.length.toString().padStart(2,'0')}</strong><small>Awaiting a review decision</small></div><div><span>Evidence needed</span><strong className="amber">{flagged.length.toString().padStart(2,'0')}</strong><small>One or more evidence flags</small></div><div><span>Inspection priority</span><strong className="red">{inspection.length.toString().padStart(2,'0')}</strong><small>Mismatch or duplicate request</small></div><div><span>Flagged refund value</span><strong>{money(flagged.reduce((s,c)=>s+c.amount,0))}</strong><small>Pending value · not proven fraud</small></div></section>
 <div className="contentgrid"><section className="queue"><div className="queueheading"><h2>Return queue <span>{cases.length}</span></h2><button className="iconbutton" aria-label="Refresh saved returns" onClick={load} disabled={loading}><RefreshCw size={17}/></button></div><div className="toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList className="bg-slate-100"><TabsTrigger value="all">All returns</TabsTrigger><TabsTrigger value="open">Open</TabsTrigger><TabsTrigger value="reviewed">Reviewed</TabsTrigger></TabsList></Tabs><label className="search"><Search size={16}/><input aria-label="Search returns" placeholder="Search returns…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {error?<div className="emptystate"><h3>Returns could not load</h3><p>{error}</p><button className="button primary" onClick={load}>Try again</button></div>:loading?<div className="emptystate" role="status">Loading saved returns…</div>:!cases.length?<div className="emptystate"><ClipboardList size={36}/><h3>Your review queue is ready.</h3><p>Load six fictional returns to try the workflow, or import your CSV.</p><button className="button primary" onClick={seed} disabled={busy}>Load sample returns</button></div>:<Table><TableHeader><TableRow><TableHead>Return / customer</TableHead><TableHead>Item / refund</TableHead><TableHead>Evidence</TableHead><TableHead>Decision</TableHead><TableHead><span className="sr-only">Review</span></TableHead></TableRow></TableHeader><TableBody>{visible.map(c=><TableRow key={c.id}><TableCell><b className="returnid">{c.id}</b><span className="cellsub">{c.customer}</span>{c.demo&&<span className="sampletag">SAMPLE</span>}</TableCell><TableCell><span className="product">{c.product}</span><span className="cellsub money">{money(c.amount)}</span></TableCell><TableCell><span className={`badge ${priority(c)==='Inspection'?'danger':priority(c)==='Evidence needed'?'warning':'clear'}`}>{priority(c)}</span><span className="cellsub">{signals(c).length?`${signals(c).length} evidence flag${signals(c).length>1?'s':''}`:'Receipt & serial verified'}</span></TableCell><TableCell><span className={`decision ${c.decision==='Open'?'':'done'}`}>{c.decision}</span></TableCell><TableCell><button className="reviewbutton" onClick={()=>open(c)}>Review</button></TableCell></TableRow>)}</TableBody></Table>}
 {!loading&&cases.length>0&&!visible.length&&<div className="emptystate">No returns match this view.</div>}<div className="queuefoot"><span>Flags guide review. They do not establish fraud.</span><span>Rules v1.0</span></div></section>
 <aside><div className="guide"><span className="guideicon"><ScanLine size={22}/></span><h2>Evidence, then a decision.</h2><p>Check what happened between the order and the refund.</p><div className="guidestep"><span>01</span><div><b>Read the flags</b><p>Every flag shows the record that needs checking.</p></div></div><div className="guidestep"><span>02</span><div><b>Verify the return</b><p>Compare receipt, serial number, and refund requests.</p></div></div><div className="guidestep"><span>03</span><div><b>Save your review</b><p>Record a decision and the evidence behind it.</p></div></div><div className="guidebottom"><ShieldCheck size={18}/><span>You make the decision.<br/>No refunds are issued by this app.</span></div></div><div className="csvcard"><Download size={20}/><h3>Start with a CSV</h3><p>Download a filled template with the exact columns to import.</p><button onClick={()=>download('returncheck-template.csv',csv(demoCases))}>Download template</button></div></aside></div>
 <footer>ReturnCheck <span>Human review. Clear evidence.</span><span>Sample records are fictional.</span></footer></main>
 <Sheet open={!!selected} onOpenChange={v=>{if(!v&&!saving)setSelected(null);}}><SheetContent className="detailpanel w-full sm:max-w-[560px] overflow-y-auto p-0"><SheetHeader className="panelhead"><p className="eyebrow">RETURN REVIEW {selected?.demo?'· SAMPLE':''}</p><SheetTitle className="text-2xl">{selected?.id}</SheetTitle><SheetDescription>{selected?.orderId} · {selected?.customer}</SheetDescription></SheetHeader>{selected&&<div className="panelbody"><div className="itemcard"><PackageCheck size={24}/><div><b>{selected.product}</b><p>{money(selected.amount)} requested refund</p></div></div><h3>Evidence flags</h3><p className="helper">Signals for review, not a fraud verdict.</p>{signals(selected).length?signals(selected).map(s=><div key={s.title} className={`signal ${s.level}`}><b>{s.title}</b><p>{s.detail}</p></div>):<div className="signal verified"><b><Check size={16}/> No flags from current rules</b><p>Receipt and serial match are recorded; no duplicate request is marked. Verify the underlying records before refunding.</p></div>}
 <h3>Source records</h3><dl className="records"><div><dt>Return shipment</dt><dd>{selected.shipment}</dd></div><div><dt>Warehouse received</dt><dd>{selected.received?'Yes':'Not recorded'}</dd></div><div><dt>Serial verification</dt><dd>{selected.serial}</dd></div><div><dt>Duplicate refund marked</dt><dd>{selected.duplicate?'Yes':'No'}</dd></div><div><dt>Customer history</dt><dd>{selected.priorReturns} returns / {selected.priorOrders} orders</dd></div></dl><p className="helper">Customer history is context only and does not trigger a flag. Records are supplied by your import.</p>
 <h3>Review decision</h3><Select value={decision} onValueChange={setDecision}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{decisions.map(d=><SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select><label className="notelabel" htmlFor="review-note">Review note</label><textarea id="review-note" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record what you checked and the next step…"/><button className="button primary savebutton" disabled={saving} onClick={save}>{saving?'Saving…':'Save review decision'}</button><p className="helper">“Ready for refund” records your decision; it does not send money.</p>
 {selected.history.length>0&&<><h3>Review history</h3><div className="history">{[...selected.history].reverse().map((h,i)=><div key={i}><b>{h.decision}</b><time>{new Date(h.date).toLocaleString()}</time>{h.note&&<p>{h.note}</p>}</div>)}</div></>}</div>}</SheetContent></Sheet>
 <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="sm:max-w-[600px]"><DialogHeader><DialogTitle>Import return records</DialogTitle><DialogDescription>Import up to 500 returns. Existing return IDs are skipped so saved reviews stay intact.</DialogDescription></DialogHeader><div className="importinstructions"><button className="button secondary" onClick={()=>download('returncheck-template.csv',csv(demoCases))}><Download size={16}/>Download CSV template</button><p>Use the template’s exact values for shipment and serial verification. Set warehouse_received and duplicate_refund to true or false.</p></div><input ref={file} type="file" accept=".csv,text/csv" onChange={e=>chooseFile(e.target.files?.[0])} className="fileinput" aria-label="Choose return CSV"/><div aria-live="polite">{fileName&&<p className="helper">{fileName}</p>}{importError&&<p className="errortext">{importError}</p>}{parsed.length>0&&<div className="preview"><b>{parsed.length} valid returns ready to import</b><p>{parsed.filter(c=>c.duplicate||c.serial==='Mismatch'||!c.received||c.serial==='Unknown').length} returns have evidence flags.</p><ul>{parsed.slice(0,3).map(c=><li key={c.id}>{c.id} · {c.product} · {money(c.amount)}</li>)}</ul></div>}</div><button className="button primary" disabled={!parsed.length||busy} onClick={commitImport}>{busy?'Importing…':'Import returns'}</button></DialogContent></Dialog>
 </>;
}
