'use client';
import { useEffect, useRef, useState } from 'react';
import { ShieldCheck, Upload, Download, PackageCheck, ScanLine, Files, Check, Search, ClipboardList, RefreshCw, Inbox, History, PanelLeftClose, House } from 'lucide-react';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Toaster,toast } from 'sonner';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarMenuBadge,SidebarInset,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { WarehouseStation,OrderRecords } from './warehouse';
import { ReturnCase,signals,priority,demoCases,csv,parseCsv,assessment,serialStatus,caseReport } from '@/lib/returns';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const decisions=['Open','Ready for refund','Request evidence','Inspect item'];
async function api(method='GET',body?:unknown){const res=await fetch('/api/returns',{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
function download(name:string,content:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function WorkspaceMenu({tab,onNavigate,onImport,onTemplate,total,openCount,reviewed}:{tab:string;onNavigate:(v:string)=>void;onImport:()=>void;onTemplate:()=>void;total:number;openCount:number;reviewed:number}){
 const {setOpenMobile}=useSidebar();
 const navigate=(v:string)=>{onNavigate(v);setOpenMobile(false);};
 return <Sidebar className="workspace-sidebar" collapsible="offcanvas"><SidebarHeader className="brandheader"><button className="brand" onClick={()=>navigate('home')} aria-label="Return to home"><span className="mark"><ShieldCheck size={22}/></span>ReturnCheck</button></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel className="navlabel">WORKSPACE</SidebarGroupLabel><SidebarMenu>{[{id:'home',label:'Home',icon:House,count:null},{id:'warehouse',label:'Warehouse station',icon:ScanLine,count:null},{id:'data',label:'Order records',icon:Files,count:null},{id:'all',label:'All returns',icon:ClipboardList,count:total},{id:'open',label:'Open reviews',icon:Inbox,count:openCount},{id:'reviewed',label:'Reviewed',icon:History,count:reviewed}].map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={tab===n.id} onClick={()=>navigate(n.id)} className="navbutton"><n.icon/><span>{n.label}</span></SidebarMenuButton>{n.count!==null&&<SidebarMenuBadge className="navcount">{n.count}</SidebarMenuBadge>}</SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup><SidebarGroupLabel className="navlabel">DATA</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton className="navbutton" onClick={()=>{onImport();setOpenMobile(false);}}><Upload/><span>Import returns</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton className="navbutton" onClick={onTemplate}><Download/><span>CSV template</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter className="navfooter"><div className="navtrust"><ShieldCheck size={19}/><p>Evidence-led review<span>Every decision stays with you.</span></p></div><div className="navuser"><span className="avatar">TT</span><div><b>Return workspace</b><span>Return operations</span></div></div></SidebarFooter></Sidebar>;
}
export default function Home(){
 const [cases,setCases]=useState<ReturnCase[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('home'),[query,setQuery]=useState(''),[selected,setSelected]=useState<ReturnCase|null>(null),[decision,setDecision]=useState('Open'),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[importOpen,setImportOpen]=useState(false),[parsed,setParsed]=useState<ReturnType<typeof parseCsv>>([]),[fileName,setFileName]=useState(''),[importError,setImportError]=useState(''),[busy,setBusy]=useState(false);
 const [bulkOpen,setBulkOpen]=useState(false),[editEvidence,setEditEvidence]=useState(false),[evidence,setEvidence]=useState({received:false,expectedSerial:'',returnedSerial:'',refunded:false,serial:'Unknown'});
 const file=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setError('');try{const d=await api();setCases(d.cases);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 function open(c:ReturnCase){setSelected(c);setDecision(c.decision);setNote(c.note||assessment(c,cases).note);setEditEvidence(false);setEvidence({received:c.received,expectedSerial:c.expectedSerial||'',returnedSerial:c.returnedSerial||'',refunded:c.refunded||false,serial:c.serial});}
 async function automate(evidenceUpdate=false){if(!selected)return;setSaving(true);try{const r=await api('PATCH',{id:selected.id,revision:selected.revision,...(evidenceUpdate?{evidence}:{applyRecommendation:true})});setSelected(r.case);setDecision(r.case.decision);setNote(r.case.note||assessment(r.case,cases).note);setEditEvidence(false);await load();toast.success(evidenceUpdate?'Evidence saved and checks rerun':'Recommendation confirmed; review note saved');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function bulk(){setBusy(true);try{const r=await api('POST',{action:'confirm_clean',ids:cleanVisible.map(c=>c.id)});await load();setBulkOpen(false);toast.success(`${r.updated} reviews confirmed. ${r.skipped} skipped. No payments issued.`);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function copyReply(c:ReturnCase){try{await navigator.clipboard.writeText(assessment(c,cases).draft);toast.success('Reply copied; not sent');}catch{toast.error('Could not copy. Select the draft text and copy it manually.');}}
 function exportCase(c:ReturnCase){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([caseReport(c,cases)],{type:'application/json'}));a.download=`${c.id.replace(/[^a-zA-Z0-9_-]/g,'_')}-review.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

 async function seed(){setBusy(true);try{const r=await api('POST',{demo:true});const res=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({demo:true})});if(!res.ok)throw new Error('Could not load sample order records');await load();toast.success(`${r.added} sample returns added${r.skipped?`; ${r.skipped} already loaded`:''}`);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!selected)return;setSaving(true);try{const r=await api('PATCH',{id:selected.id,revision:selected.revision,decision,note});setCases(old=>old.map(c=>c.id===r.case.id?r.case:c));setSelected(r.case);toast.success('Review saved');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function chooseFile(f?:File){setImportError('');setParsed([]);if(!f)return;setFileName(f.name);if(f.size>1000000){setImportError('Choose a CSV smaller than 1 MB');return;}try{setParsed(parseCsv(await f.text()));}catch(e){setImportError((e as Error).message);}}
 async function commitImport(){setBusy(true);try{const r=await api('POST',{cases:parsed});await load();setImportOpen(false);setParsed([]);setTab('all');toast.success(`${r.added} returns imported. ${r.skipped} existing IDs skipped.`);}catch(e){setImportError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'list_return_cases',description:'Read saved return cases and evidence flags in the current review workspace.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const d=await api();return {cases:d.cases.map((c:ReturnCase)=>({id:c.id,decision:c.decision,flags:signals(c)}))};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 const openCases=cases.filter(c=>c.decision==='Open'),flagged=openCases.filter(c=>signals(c).length),inspection=openCases.filter(c=>priority(c)==='Inspection');
 const visible=cases.filter(c=>(tab==='all'||tab==='open'&&c.decision==='Open'||tab==='reviewed'&&c.decision!=='Open')&&`${c.id} ${c.orderId} ${c.customer} ${c.product}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const rank=(c:ReturnCase)=>c.decision!=='Open'?3:priority(c)==='Inspection'?0:priority(c)==='Evidence needed'?1:2;return rank(a)-rank(b);});
 const cleanVisible=visible.filter(c=>c.decision==='Open'&&assessment(c,cases).action==='Ready for refund');
 return <SidebarProvider style={{'--sidebar-width':'248px'} as React.CSSProperties}><Toaster richColors position="bottom-right"/><WorkspaceMenu tab={tab} onNavigate={v=>{setTab(v);setQuery('');setSelected(null);}} onImport={()=>{setImportOpen(true);setImportError('');}} onTemplate={()=>download('returncheck-template.csv',csv(demoCases))} total={cases.length} openCount={openCases.length} reviewed={cases.length-openCases.length}/><SidebarInset className="app-main"><header className="topbar"><div className="headerpath"><SidebarTrigger className="menutoggle"/><span>Workspace</span><span className="pathdivider">/</span><b>{tab==='warehouse'?'Warehouse station':tab==='data'?'Order records':tab==='home'?'Home':tab==='all'?'All returns':tab==='open'?'Open reviews':'Reviewed'}</b></div><span className="topmeta">RETURN OPERATIONS</span></header>
 {tab==='home'?<section className="home-screen" aria-labelledby="home-title"><div className="home-topline"><span>RETURNCHECK</span><span>THE RETURN REVIEW WORKSPACE</span></div><div className="home-intro"><p className="home-kicker">A little clarity goes a long way.</p><h1 id="home-title">Before the refund,<br/><em>comes the evidence.</em></h1><p className="home-copy">An order. A shipment. A returned item.<br/>Bring the records together, see what needs checking,<br className="desktopbreak"/> and make the next decision with confidence.</p><button className="home-enter" onClick={()=>setTab('all')}><ClipboardList size={18}/>Open return workspace</button><span className="home-footnote">Clear signals. Human decisions.</span></div><div className="home-baseline"><div><span>01</span><b>Bring the records together.</b></div><div><span>02</span><b>See what needs checking.</b></div><div><span>03</span><b>Make the next decision.</b></div></div></section>:tab==='warehouse'?<WarehouseStation cases={cases} onRefresh={load} onOpen={open} onDemo={seed} onOrders={()=>setTab('data')}/>:tab==='data'?<OrderRecords onRefresh={load}/>:<div className="workspace"><div className="pagehead"><div><p className="eyebrow">WORKSPACE / RETURNS</p><h1>{tab==='all'?'Return review':tab==='open'?'Open reviews':'Reviewed returns'}</h1><p className="subtitle">Checks run automatically. Confirm prepared reviews; work only on exceptions.</p></div><div className="actions"><button className="button secondary" onClick={seed} disabled={busy||loading}><Files size={16}/>Load sample returns</button><button className="button primary" onClick={()=>{setImportOpen(true);setImportError('');}}><Upload size={16}/>Import CSV</button></div></div>
 <section className="metrics" aria-label="Return summary"><div><span>Open returns</span><strong>{openCases.length.toString().padStart(2,'0')}</strong><small>Awaiting a review decision</small></div><div><span>Evidence needed</span><strong className="amber">{flagged.length.toString().padStart(2,'0')}</strong><small>One or more evidence flags</small></div><div><span>Inspection priority</span><strong className="red">{inspection.length.toString().padStart(2,'0')}</strong><small>Mismatch or duplicate request</small></div><div><span>Flagged refund value</span><strong>{money(flagged.reduce((s,c)=>s+c.amount,0))}</strong><small>Pending value · not proven fraud</small></div></section>
 {cases.length>0&&<div className="automationbar"><div><span className="automationlabel">AUTOMATIC REVIEW</span><h2>{cleanVisible.length} returns ready for one-step confirmation</h2><p>Records checked, next actions prepared, and review notes drafted. No payment is issued.</p></div><button className="button primary" disabled={!cleanVisible.length||busy||loading} onClick={()=>setBulkOpen(true)}>Confirm {cleanVisible.length} ready reviews</button></div>}<div className="contentgrid"><section className="queue"><div className="queueheading"><h2>Return queue <span>{cases.length}</span></h2><button className="iconbutton" aria-label="Refresh saved returns" onClick={load} disabled={loading}><RefreshCw size={17}/></button></div><div className="toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList className="bg-slate-100"><TabsTrigger value="all">All returns</TabsTrigger><TabsTrigger value="open">Open</TabsTrigger><TabsTrigger value="reviewed">Reviewed</TabsTrigger></TabsList></Tabs><label className="search"><Search size={16}/><input aria-label="Search returns" placeholder="Search returns…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {error?<div className="emptystate"><h3>Returns could not load</h3><p>{error}</p><button className="button primary" onClick={load}>Try again</button></div>:loading?<div className="emptystate" role="status">Loading saved returns…</div>:!cases.length?<div className="emptystate"><ClipboardList size={36}/><h3>Your review queue is ready.</h3><p>Load six fictional returns to try the workflow, or import your CSV.</p><button className="button primary" onClick={seed} disabled={busy}>Load sample returns</button></div>:<Table><TableHeader><TableRow><TableHead>Return / customer</TableHead><TableHead>Item / refund</TableHead><TableHead>Evidence</TableHead><TableHead>Next action / decision</TableHead><TableHead><span className="sr-only">Review</span></TableHead></TableRow></TableHeader><TableBody>{visible.map(c=><TableRow key={c.id}><TableCell><b className="returnid">{c.id}</b><span className="cellsub">{c.customer}</span>{c.demo&&<span className="sampletag">SAMPLE</span>}</TableCell><TableCell><span className="product">{c.product}</span><span className="cellsub money">{money(c.amount)}</span></TableCell><TableCell><span className={`badge ${priority(c)==='Inspection'?'danger':priority(c)==='Evidence needed'?'warning':'clear'}`}>{priority(c)}</span><span className="cellsub">{signals(c).length?`${signals(c).length} evidence flag${signals(c).length>1?'s':''}`:'Receipt & serial verified'}</span></TableCell><TableCell><span className="nextaction">{assessment(c,cases).next}</span><span className={`decision ${c.decision==='Open'?'':'done'}`}>{c.decision}</span></TableCell><TableCell><button className="reviewbutton" onClick={()=>open(c)}>Open case</button></TableCell></TableRow>)}</TableBody></Table>}
 {!loading&&cases.length>0&&!visible.length&&<div className="emptystate">No returns match this view.</div>}<div className="queuefoot"><span>Flags guide review. They do not establish fraud.</span><span>Rules v3.0</span></div></section>
 <aside><div className="guide"><span className="guideicon"><ScanLine size={22}/></span><h2>Prepared for you.</h2><p>Import once. ReturnCheck assembles the case and prepares the next step.</p><div className="guidestep"><span>01</span><div><b>Automatic checks</b><p>Serials, receipt, prior refunds, and overlapping requests.</p></div></div><div className="guidestep"><span>02</span><div><b>Prepared case</b><p>Evidence, next action, review note, and customer reply.</p></div></div><div className="guidestep"><span>03</span><div><b>One-step confirmation</b><p>Confirm ready reviews together. Handle exceptions individually.</p></div></div><div className="guidebottom"><ShieldCheck size={18}/><span>You make the decision.<br/>No refunds are issued by this app.</span></div></div><div className="csvcard"><Download size={20}/><h3>Start with a CSV</h3><p>Download a filled template with the exact columns to import.</p><button onClick={()=>download('returncheck-template.csv',csv(demoCases))}>Download template</button></div></aside></div>
 <footer>ReturnCheck <span>Human review. Clear evidence.</span><span>Sample records are fictional.</span></footer></div>}</SidebarInset>
 <Sheet open={!!selected} onOpenChange={v=>{if(!v&&!saving)setSelected(null);}}><SheetContent className="detailpanel w-full sm:max-w-[560px] overflow-y-auto p-0"><SheetHeader className="panelhead"><button className="backqueue" disabled={saving} onClick={()=>setSelected(null)}><PanelLeftClose size={16}/>Back to return queue</button><p className="eyebrow">RETURN REVIEW {selected?.demo?'· SAMPLE':''}</p><SheetTitle className="text-2xl">{selected?.id}</SheetTitle><SheetDescription>{selected?.orderId} · {selected?.customer}</SheetDescription></SheetHeader>{selected&&<div className="panelbody"><div className="itemcard"><PackageCheck size={24}/><div><b>{selected.product}</b><p>{money(selected.amount)} requested refund</p></div></div><div className="preparedcase"><span className="automationlabel">PREPARED REVIEW</span><h2>{assessment(selected,cases).next}</h2><p>{assessment(selected,cases).reason}</p><button className="button primary" disabled={saving||loading} onClick={()=>automate()}>{saving?'Saving…':`Confirm: ${assessment(selected,cases).action}`}</button><small>Saves the decision and prepared note. No refund or message is sent.</small></div><h3>Evidence flags</h3><p className="helper">Signals for review, not a fraud verdict.</p>{signals(selected).length?signals(selected).map(s=><div key={s.title} className={`signal ${s.level}`}><b>{s.title}</b><p>{s.detail}</p></div>):<div className="signal verified"><b><Check size={16}/> No flags from current rules</b><p>Receipt and serial match are recorded; no duplicate request is marked. Verify the underlying records before refunding.</p></div>}
 <h3>Source records</h3><dl className="records"><div><dt>Return shipment</dt><dd>{selected.shipment}</dd></div><div><dt>Warehouse received</dt><dd>{selected.received?'Yes':'Not recorded'}</dd></div><div><dt>Serial verification</dt><dd>{serialStatus(selected)}</dd></div><div><dt>Duplicate refund marked</dt><dd>{selected.duplicate?'Yes':'No'}</dd></div><div><dt>Expected serial</dt><dd>{selected.expectedSerial||'Not supplied'}</dd></div><div><dt>Returned serial</dt><dd>{selected.returnedSerial||'Not supplied'}</dd></div><div><dt>Original amount paid</dt><dd>{selected.amountPaid!==undefined?money(selected.amountPaid):'Not supplied'}</dd></div><div><dt>Previously refunded amount</dt><dd>{selected.amountRefunded!==undefined?money(selected.amountRefunded):'Not supplied'}</dd></div><div><dt>Order source</dt><dd>{selected.orderSource||'Return import'}</dd></div><div><dt>Tracking record</dt><dd>{selected.trackingNumber||'Not supplied'}</dd></div><div><dt>Prior refund recorded</dt><dd>{selected.refunded?'Yes':'No'}</dd></div><div><dt>Linked requests</dt><dd>{selected.relatedIds?.join(', ')||'None found'}</dd></div><div><dt>Customer history</dt><dd>{selected.priorReturns} returns / {selected.priorOrders} orders</dd></div></dl><p className="helper">Customer history is context only and does not trigger a flag. Records are supplied by your import.</p>
 <button className="button secondary" onClick={()=>setEditEvidence(!editEvidence)}>{editEvidence?'Cancel evidence edit':'Update evidence and rerun checks'}</button>{editEvidence&&<div className="evidenceeditor"><label><Checkbox checked={evidence.received} onCheckedChange={v=>setEvidence({...evidence,received:v===true})}/>Warehouse receipt confirmed</label><label><Checkbox checked={evidence.refunded} onCheckedChange={v=>setEvidence({...evidence,refunded:v===true})}/>Refund already issued</label><label>Expected serial<input disabled={!!selected.orderSource} title={selected.orderSource?'Original serial is supplied by the imported order record':undefined} value={evidence.expectedSerial} maxLength={100} onChange={e=>setEvidence({...evidence,expectedSerial:e.target.value})}/></label><label>Returned serial<input value={evidence.returnedSerial} maxLength={100} onChange={e=>setEvidence({...evidence,returnedSerial:e.target.value})}/></label><label>Recorded item verification (when serials are unavailable)</label><Select value={evidence.serial} onValueChange={v=>setEvidence({...evidence,serial:v})}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{['Match','Mismatch','Unknown'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><p className="helper">Original order serials are updated through Order records. Entered serials take precedence over a manual match status. Saving evidence reopens the review so a previous decision can be rechecked.</p><button className="button primary" disabled={saving} onClick={()=>automate(true)}>Save evidence and rerun</button></div>}
 <h3>Prepared customer reply</h3><div className="replydraft"><p>{assessment(selected,cases).draft}</p><button className="reviewbutton" onClick={()=>copyReply(selected)}>Copy reply</button><span>Draft only · not sent</span></div><button className="button secondary exportcase" onClick={()=>exportCase(selected)}><Download size={16}/>Export complete case</button><h3>Adjust the prepared decision</h3><Select value={decision} onValueChange={setDecision}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{decisions.map(d=><SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select><label className="notelabel" htmlFor="review-note">Review note</label><textarea id="review-note" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record what you checked and the next step…"/><button className="button primary savebutton" disabled={saving} onClick={save}>{saving?'Saving…':'Save review decision'}</button><p className="helper">“Ready for refund” records your decision; it does not send money.</p>
 {selected.history.length>0&&<><h3>Review history</h3><div className="history">{[...selected.history].reverse().map((h,i)=><div key={i}><b>{h.decision}</b><time>{new Date(h.date).toLocaleString()}</time>{h.note&&<p>{h.note}</p>}</div>)}</div></>}</div>}</SheetContent></Sheet>
 <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="sm:max-w-[600px]"><DialogHeader><DialogTitle>Import return records</DialogTitle><DialogDescription>Import up to 500 returns. Existing return IDs are skipped so saved reviews stay intact.</DialogDescription></DialogHeader><div className="importinstructions"><button className="button secondary" onClick={()=>download('returncheck-template.csv',csv(demoCases))}><Download size={16}/>Download CSV template</button><p>Use the template’s exact values for shipment and serial verification. Set warehouse_received and duplicate_refund to true or false. Optional expected_serial, returned_serial, and refund_issued columns enable additional checks.</p></div><input ref={file} type="file" accept=".csv,text/csv" onChange={e=>chooseFile(e.target.files?.[0])} className="fileinput" aria-label="Choose return CSV"/><div aria-live="polite">{fileName&&<p className="helper">{fileName}</p>}{importError&&<p className="errortext">{importError}</p>}{parsed.length>0&&<div className="preview"><b>{parsed.length} valid returns ready to import</b><p>{parsed.filter(c=>c.duplicate||c.serial==='Mismatch'||!c.received||c.serial==='Unknown').length} returns have evidence flags.</p><ul>{parsed.slice(0,3).map(c=><li key={c.id}>{c.id} · {c.product} · {money(c.amount)}</li>)}</ul></div>}</div><button className="button primary" disabled={!parsed.length||busy} onClick={commitImport}>{busy?'Importing…':'Import returns'}</button></DialogContent></Dialog>
 <Dialog open={bulkOpen} onOpenChange={setBulkOpen}><DialogContent><DialogHeader><DialogTitle>Confirm {cleanVisible.length} prepared reviews?</DialogTitle><DialogDescription>For the current view, returns with receipt and item verification recorded and no evidence flags will be marked ready for refund. Each gets a prepared review note and history entry. No money is sent.</DialogDescription></DialogHeader><div className="bulksummary">{cleanVisible.slice(0,6).map(c=><div key={c.id}><b>{c.id}</b><span>{c.customer}</span><span>{money(c.amount)}</span></div>)}{cleanVisible.length>6&&<p>And {cleanVisible.length-6} more</p>}</div><button className="button primary" disabled={busy||!cleanVisible.length} onClick={bulk}>{busy?'Confirming…':'Confirm prepared reviews'}</button></DialogContent></Dialog></SidebarProvider>;
}
